import React, { useState, useEffect } from 'react';
import { supabase } from './supabaseClient';
import { getCertificatesForUser, downloadCertificateAsImage } from './utils/certificateUtils';
import CertificateTemplate from './components/CertificateTemplate';
import './AuthorCertificates.css';

const AuthorCertificates = () => {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedCertificate, setSelectedCertificate] = useState(null);
  const [previewMode, setPreviewMode] = useState(false);

  useEffect(() => {
    fetchUserCertificates();
  }, []);

  const fetchUserCertificates = async () => {
    try {
      setLoading(true);
      setError('');

      // Get current user ID from localStorage
      const userData = localStorage.getItem("ictest26_user");
      let userId;
      
      try {
        const userObj = JSON.parse(userData);
        userId = userObj.login_id;
      } catch (error) {
        setError('Unable to identify user. Please log in again.');
        return;
      }

      if (!userId) {
        setError('User ID not found. Please log in again.');
        return;
      }

      const userCertificates = await getCertificatesForUser(supabase, userId);
      setCertificates(userCertificates);
      
    } catch (err) {
      console.error('Error fetching certificates:', err);
      setError('Failed to load certificates. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // Removed PDF download function - only PNG certificates now

  const handleDownloadImage = async (certificate) => {
    try {
      // If certificate has stored URL, download directly
      if (certificate.image_url) {
        const link = document.createElement('a');
        link.href = certificate.image_url;
        link.download = `${certificate.recipient_name}_${certificate.certificate_type}_certificate.png`;
        link.target = '_blank';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      } else {
        setError('Certificate image not found. Please contact admin.');
      }
    } catch (err) {
      console.error('Error downloading certificate image:', err);
      setError('Failed to download certificate image. Please try again.');
    }
  };

  const handlePreview = (certificate) => {
    setSelectedCertificate(certificate);
    setPreviewMode(true);
  };

  const closePreview = () => {
    setSelectedCertificate(null);
    setPreviewMode(false);
  };

  const getCertificateTypeLabel = (type) => {
    const labels = {
      'participation': 'Certificate of Participation',
      'author': 'Certificate of Appreciation (Author)',
      'reviewer': 'Certificate of Appreciation (Reviewer)',
      'session_chair': 'Certificate of Appreciation (Session Chair)'
    };
    return labels[type] || type;
  };

  const getCertificateTypeColor = (type) => {
    const colors = {
      'participation': '#2e7fd6',
      'author': '#2ecc71',
      'reviewer': '#e67e22',
      'session_chair': '#9b59b6'
    };
    return colors[type] || '#6c757d';
  };

  // Group certificates by type
  const groupedCertificates = certificates.reduce((groups, cert) => {
    const type = cert.certificate_type;
    if (!groups[type]) {
      groups[type] = [];
    }
    groups[type].push(cert);
    return groups;
  }, {});

  if (loading) {
    return (
      <div className="author-certificates">
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading your certificates...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="author-certificates">
      <div className="certificates-header">
        <div className="header-content">
          <div className="header-text">
            <h1>Certificates</h1>
            <p className="certificates-subtitle">View and download your ICTEST 2026 certificates</p>
          </div>
        </div>
      </div>

      {error && (
        <div className="error-message">
          <span className="error-icon">⚠️</span>
          {error}
          <button className="retry-button" onClick={fetchUserCertificates}>
            Retry
          </button>
        </div>
      )}

      {certificates.length === 0 && !error && (
        <div className="no-certificates">
          <div className="no-certificates-icon">📜</div>
          <h3>No Certificates Found</h3>
          <p>You don't have any certificates yet. Certificates will appear here once they are generated by the conference administrators.</p>
          <p className="help-text">
            If you believe you should have certificates, please contact the conference organizers.
          </p>
        </div>
      )}

      {certificates.length > 0 && (
        <div className="certificates-container">
          {Object.entries(groupedCertificates).map(([type, certs]) => (
            <div key={type} className="certificate-section">
              <div className="section-header">
                <h2 className="section-title" style={{ color: getCertificateTypeColor(type) }}>
                  {getCertificateTypeLabel(type)}
                </h2>
                <span className="certificate-count">{certs.length} certificate{certs.length > 1 ? 's' : ''}</span>
              </div>
              
              <div className="certificates-grid">
                {certs.map((certificate) => (
                  <div key={certificate.id} className="certificate-card">
                    <div className="certificate-info">
                      <h3 className="recipient-name">{certificate.recipient_name}</h3>
                      {certificate.paper_title && (
                        <p className="paper-title">"{certificate.paper_title}"</p>
                      )}
                    </div>

                    <div className="certificate-actions">
                      <button 
                        className="action-button secondary"
                        onClick={() => handlePreview(certificate)}
                      >
                        Preview
                      </button>
                      <button 
                        className="action-button primary"
                        onClick={() => handleDownloadImage(certificate)}
                      >
                        Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Preview Modal */}
      {previewMode && selectedCertificate && (
        <div className="preview-modal" onClick={closePreview}>
          <div className="preview-content" onClick={(e) => e.stopPropagation()}>
            <button className="close-button" onClick={closePreview}>×</button>
            <div className="preview-certificate">
              <CertificateTemplate
                type={selectedCertificate.certificate_type}
                recipientName={selectedCertificate.recipient_name}
                paperTitle={selectedCertificate.paper_title}
                isPreview={true}
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AuthorCertificates;